basic_settings:
  site_title: Factory Town
  favicon_image: /images/favicons/favicon.ico

header_settings:
  logo_image: /images/factory-town-logo.png
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about'

footer_settings:
  footer_tagline:

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 20
  content_alignment: bottom

contact_settings:
  form_action: 'https://formspree.io/hi@factory.town'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#2D2D2D'
  background_alt_color: '#2D2D2D'
  text_dark_color: '#939393'
  text_medium_color: '#E6E6E6'
  text_light_color: '#939393'
  accent_color: '#939393'
  border_color: '#dddddd'
  overlay_background_color: '#E6E6E6'
  overlay_text_color: '#000000'
  overlay_accent_color: '#2D2D2D'
  error_color: '#D64541'

font_settings:
  font_embed: '  <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Yeseva+One" rel="stylesheet"> '
  title_font: ' "M PLUS 1p", sans-serif '
  body_font: ' "M PLUS 1p", sans-serif '
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 14
    large_size: 15
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 24
    large_size: 28
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 13
    medium_size: 15
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 20
    medium_size: 22
    large_size: 24
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 14
    medium_size: 14
    large_size: 16
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""